# baseURL = "https://blog-staging.samrhea.com/"
baseURL = "https://blog.samrhea.com/"
languageCode = "en-us"
title = "Sam Rhea's blog"
theme = "hugo-cactus-theme"

[params]
        name = "Sam Rhea"
        description = "Sam Rhea's blog"
        bio = "A Texan in Portugal testing drafts. "
        # Enter optionally your twitter account
        twitter = "LakeAustinBlvd"
        enableRSS = true
        avatar = "/static/avatar/avatar.png"

        # Integrate Javascript files or stylesheets by adding the url to the external assets or by
        # linking local files with their path relative to the static folder, e.g. "css/styles.css"
        customCSS = []
        customJS  = []

        # The variables below are optionally too and can be used to
        # translate or customize each string of the theme.

        # Navigation links
        home = ""
        subscribe = "RSS Feed"
        # Pagination links
        paginate = ""
        olderPosts = ""
        newerPosts = ""
        readMore = ""
        copyright = ""
        # Sharing options and author information in posts
        aboutAuthor = "A Texan in Portugal"
        tweet = ""
        share = ""
        # 404 page
        title404 = ""
        subtitle404 = ""

        # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
        iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/LakeAustinBlvd"
    github = "https://github.com/AustinCorridor/"