account_id = "eca95c4515a39540cafc79d7b2561a25"
name = "blog-samrhea"
type = "webpack"
route = "blog.samrhea.com/*"
workers_dev = false
zone_id = "629e8bfaf0bb8becf800b692bb4a5443"

[env.staging]
name = "blog-staging"
route = "blog-staging.samrhea.com/*"

[site]
bucket = "public"
entry-point = "workers-site"