name: Deploy to Workers Staging

on:
  push:
    branches:
      - 'draft/*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
  
      - name: Install NPM
        run: npm install -g yarn
      
      - name: Yarn
        run: yarn install --frozen-lockfile

      - name: Install gatsby-cli
        run: npm install -g gatsby-cli

      - name: Build site
        run: gatsby build
      
      - name: Install Wrangler
        run: npm i @cloudflare/wrangler -g

      - name: Config Wrangler
        run: CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} wrangler publish --env staging
